application: portal-pt
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "7d"

handlers:
- url: /
  static_files: web/portal.html
  upload: web/portal.html

- url: /
  static_dir: web

- url: /.*
  static_files: html/404.html
  upload: html/404.html